### ISSUE TITLE
matplotlib version?

### ISSUE THREAD

**Issue by mncfletcher** [ykai16/Lollipop#3]
Hello,

I'm trying to run train_models.py and get the following error:

`python ./train_models.py -t ./data/K562_training_forMED211_20190603.txt -o ./K5orMED211_20190603
/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Reading in features...
Negative samples were 5.0 times more than the positive loops...
./train_models.py:87: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  X = data.iloc[:,4:].as_matrix()
Training model...
Traceback (most recent call last):
  File "./train_models.py", line 128, in <module>
    main(sys.argv)
  File "./train_models.py", line 99, in main
    plt.figure()
  File "/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)
  File "/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)
  File "/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)
  File "/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 236, in __init__
    _create_qApp()
  File "/home/fletcher/.conda/envs/lollipop/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 144, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable`

Based on the traceback it looks like I might not have the right matplotlib version - would you know versions of matplotlib that work?

Thanks in advance!

**Comment by mncfletcher** [comment]
Ah my bad - based on https://stackoverflow.com/questions/43452136/why-can-i-not-plot-using-python-on-repl-it it's because I'm running it on a server without a GUI. I've added:

`import matplotlib as mpl
mpl.use('Agg')`

As suggested in the SO post and am rerunning now.

**Comment by mncfletcher** [comment]
...and you also need to create the output folder defined in -o first, on top of the mpl.use('Agg') - but everything works now!

**Comment by ykai16** [comment]
> ...and you also need to create the output folder defined in -o first, on top of the mpl.use('Agg') - but everything works now!

Glad to see it works. Thanks!
